#%RAML 0.8
title: SalesForce Customers API
version: v0.0.1
baseUri: http://localhost/{apiVersion}/
protocols: [ HTTP, HTTPS ]
mediaType: application/json
documentation:
  - title: SalesForce API - Summary
    content: This console exposes the Accenture Digital/1 SalesForce API 

baseUriParameters:
  apiVersion:
    type: string
    required: true

traits:
  -  thirdPartyStateful:
      description: third Party
      headers:
        thirdPartyCorrelationId:
          type: string
          required: true

  - commonHeader:
      description: Common header paramaters
      headers:
        orderId:
          type: string
          required: false

/customersummary:
  description: Retrieve Customer information and thir Orders
  get:
    description: Retrieves an existing customer and orders by customerId
    queryParameters:
      customerId:
        description: customer id
        example: 0032400000BJRbKAAX
      lastModified:
        description: last modified
        example: 2016-05-20T21:17:21.000Z
    responses:
      200:
        description: Success
        body:
          application/json: